# Generated by Django 3.2.6 on 2021-10-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created',), 'verbose_name': 'Article management', 'verbose_name_plural': 'Article management'},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'category management', 'verbose_name_plural': 'category management'},
        ),
    ]
